In [45]:
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df = pd.DataFrame(data = datasets.load_breast_cancer().data,columns = datasets.load_breast_cancer().feature_names)

In [47]:
df['target'] = datasets.load_breast_cancer().target

In [48]:
df['target'].value_counts()

1    357
0    212
Name: target, dtype: int64

In [49]:
df.head(3)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   
2        19.69         21.25           130.0     1203.0          0.10960   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33            184.6      2019.0   
1                 0.05667  ...          23.41            158.8      1956.0   
2                 0.05999  ...          25.53            152.5      1709.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  

[3 rows x 31 columns]

## Preparing Train and Test data

In [50]:
X = df.drop(columns=['target']).values
y = df['target'].values

In [51]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=28)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(398, 30)
(398,)
(171, 30)
(171,)


## Sklearn Logistic regression

In [52]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=500)
logreg.fit(X_train,y_train)

y_pred = logreg.predict(X_test)
y_prob = logreg.predict_proba(X_test)

C:\Users\abhid\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [53]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])

In [54]:
y_prob

array([[9.98846913e-01, 1.15308688e-03],
       [4.25506750e-02, 9.57449325e-01],
       [2.67908239e-04, 9.99732092e-01],
       [9.08299545e-02, 9.09170045e-01],
       [2.58290536e-03, 9.97417095e-01],
       [2.27435308e-02, 9.77256469e-01],
       [5.03043080e-03, 9.94969569e-01],
       [7.90805547e-04, 9.99209194e-01],
       [2.67042647e-03, 9.97329574e-01],
       [1.00000000e+00, 6.16981801e-11],
       [3.79989998e-03, 9.96200100e-01],
       [1.00000000e+00, 2.70927318e-24],
       [5.98612200e-03, 9.94013878e-01],
       [9.46557791e-01, 5.34422088e-02],
       [9.99998826e-01, 1.17411208e-06],
       [1.42779483e-03, 9.98572205e-01],
       [4.37809846e-02, 9.56219015e-01],
       [5.77140738e-01, 4.22859262e-01],
       [9.99995727e-01, 4.27329528e-06],
       [9.30213763e-01, 6.97862367e-02],
       [9.99999999e-01, 1.34521927e-09],
       [9.99999939e-01, 6.06339282e-08],
       [1.10799156e-02, 9.88920084e-01],
       [2.17717018e-01, 7.82282982e-01],
       [9.999761

In [55]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print(accuracy_score(y_test,y_pred))
print()
print(confusion_matrix(y_test,y_pred))
print()
print(classification_report(y_test,y_pred))

0.9473684210526315

[[ 56   3]
 [  6 106]]

              precision    recall  f1-score   support

           0       0.90      0.95      0.93        59
           1       0.97      0.95      0.96       112

    accuracy                           0.95       171
   macro avg       0.94      0.95      0.94       171
weighted avg       0.95      0.95      0.95       171



## Does Logistic Regression work if target is string instead of int?

In [56]:
df['targetstr'] = df['target'].apply(lambda x: 'Cancer' if x==1 else 'Not Cancer')

In [57]:
df['targetstr'].value_counts()

Cancer        357
Not Cancer    212
Name: targetstr, dtype: int64

In [58]:
X = df.drop(columns=['target','targetstr']).values
y = df['targetstr'].values

# splitting into train and test sets
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=28)

# Model fitting
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=500)
logreg.fit(X_train,y_train)

y_pred = logreg.predict(X_test)
y_prob = logreg.predict_proba(X_test)

print(y_pred)
print('-'*50)
print(y_prob)

['Not Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer'
 'Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Not Cancer' 'Cancer'
 'Not Cancer' 'Not Cancer' 'Cancer' 'Cancer' 'Not Cancer' 'Not Cancer'
 'Not Cancer' 'Not Cancer' 'Not Cancer' 'Cancer' 'Cancer' 'Not Cancer'
 'Not Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer'
 'Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Cancer'
 'Not Cancer' 'Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Not Cancer'
 'Not Cancer' 'Not Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Cancer'
 'Not Cancer' 'Cancer' 'Not Cancer' 'Not Cancer' 'Cancer' 'Cancer'
 'Not Cancer' 'Cancer' 'Not Cancer' 'Not Cancer' 'Cancer' 'Not Cancer'
 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer'
 'Cancer' 'Not Cancer' 'Cancer' 'Cancer' 'Cancer' 'Not Cancer' 'Cancer'
 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Cancer' 'Not Cancer' 'Cancer'
 'Not Cancer' 'Cancer' 'Not Cancer' 'Cancer' 'Not Cancer' 'Cancer'
 'Cancer' 'Cancer' 'Cancer' 'Ca

C:\Users\abhid\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [59]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      Cancer       0.97      0.95      0.96       112
  Not Cancer       0.90      0.95      0.93        59

    accuracy                           0.95       171
   macro avg       0.94      0.95      0.94       171
weighted avg       0.95      0.95      0.95       171



# Creating own Logistic Class

In [149]:
import numpy

class MyLogistic:
    
    def __init__(self,rate=.01,epochs=100):
        self.rate = rate
        self.epochs = epochs
        self.coef = None
        self.intercept = None
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
        
    def fit(self,X,y):
        
        rows,cols = X.shape
        
        # initialise coeffecient and intercept
        self.intercept = 0
        self.coef = np.ones(cols)
        
        for _ in range(self.epochs):
            z = np.dot(X,self.coef) + self.intercept
            y_hat = self.sigmoid(z)
            
            
            # slope calculations
            loss_slope_intercept = np.sum(y_hat - y)/rows
            loss_slope_coef = np.dot((y_hat - y),X)/rows
        
        
            # updating intercept
            self.intercept = self.intercept - (self.rate*loss_slope_intercept)
    
            # updating coeffecients
            self.coef = self.coef - (self.rate*loss_slope_coef)
               
    
    def predict_proba(self,X):
        y_proba = self.sigmoid(np.dot(X,self.coef) + self.intercept)
        y_pred = [0 if i<=0.5 else 1 for i in y_proba]
        return y_proba
        
    def predict(self,X):
        y_proba = self.sigmoid(np.dot(X,self.coef) + self.intercept)
        y_pred = [0 if i<=0.5 else 1 for i in y_proba]
        return y_pred

In [150]:
model = MyLogistic(rate=0.01,epochs=500)

In [151]:
X = df.drop(columns=['target','targetstr']).values
y = df['target'].values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=28)


In [152]:
model.fit(X_train,y_train)

C:\Users\abhid\AppData\Local\Temp\ipykernel_13420\757824119.py:13: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


In [153]:
y_pred2 = model.predict(X_test)

C:\Users\abhid\AppData\Local\Temp\ipykernel_13420\757824119.py:13: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


In [154]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.95      0.88      0.91        59
           1       0.94      0.97      0.96       112

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171

